apiVersion: v1
kind: ServiceAccount
metadata:
  name: defb
  namespace: ingress-nginx
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: defb-configmap-manage
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: defb-configmap-manage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: defb-configmap-manage
subjects:
- kind: ServiceAccount
  namespace: ingress-nginx
  name: defb
---
apiVersion: v1
kind: Service
metadata:
  name: defb
  namespace: ingress-nginx
spec:
  selector:
    app: defb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: defb
  namespace: ingress-nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: defb
    spec:
      serviceAccountName: defb
      terminationGracePeriodSeconds: 10
      containers:
        - name: defb
          image: plugandtrade/defb
          imagePullPolicy: Always
          env:
            - name: K8S_MODE
              value: "in_cluster"
          ports:
            - name: http
              containerPort: 4000
